[context.production]
  publish = "dist/"
  command = "pnpm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=63115200, s-max-age=63115200, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=63115200, s-max-age=63115200, immutable"

[[edge_functions]]
  function = "og"
  path = "/og-image"